#!/usr/bin/env node
/**
 * Generates static squad JSON files for the 5-a-Side World Cup game.
 * Based on real World Cup squads with historically-accurate player ratings.
 * Run: node scripts/generate-squads.js
 */

const fs = require("fs");
const path = require("path");

const squads = {
  brazil_2002: {
    team: "Brazil",
    year: 2002,
    nation_code: "BR",
    flag: "🇧🇷",
    players: [
      { id: "ronaldo_2002", name: "Ronaldo", position: "FWD", age_at_tournament: 25, overall: 97 },
      { id: "rivaldo_2002", name: "Rivaldo", position: "MID", age_at_tournament: 30, overall: 91 },
      { id: "ronaldinho_2002", name: "Ronaldinho", position: "MID", age_at_tournament: 22, overall: 88 },
      { id: "roberto_carlos_2002", name: "Roberto Carlos", position: "DEF", age_at_tournament: 29, overall: 89 },
      { id: "cafu_2002", name: "Cafu", position: "DEF", age_at_tournament: 32, overall: 87 },
      { id: "lucio_2002", name: "Lúcio", position: "DEF", age_at_tournament: 24, overall: 83 },
      { id: "kleberson_2002", name: "Kleberson", position: "MID", age_at_tournament: 23, overall: 77 },
      { id: "gilberto_silva_2002", name: "Gilberto Silva", position: "MID", age_at_tournament: 25, overall: 79 },
      { id: "edilson_2002", name: "Edilson", position: "DEF", age_at_tournament: 31, overall: 75 },
      { id: "anderson_luis_2002", name: "Anderson Luís", position: "DEF", age_at_tournament: 27, overall: 74 },
      { id: "marcos_2002", name: "Marcos", position: "GK", age_at_tournament: 30, overall: 83 },
      { id: "dida_2002", name: "Dida", position: "GK", age_at_tournament: 28, overall: 80 },
      { id: "denilson_2002", name: "Denílson", position: "MID", age_at_tournament: 24, overall: 76 },
      { id: "juninho_2002", name: "Juninho Paulista", position: "MID", age_at_tournament: 29, overall: 79 },
      { id: "edilson_fwd_2002", name: "Edilson (FWD)", position: "FWD", age_at_tournament: 31, overall: 74 },
      { id: "luizao_2002", name: "Luizão", position: "FWD", age_at_tournament: 28, overall: 72 },
    ],
  },
  brazil_1970: {
    team: "Brazil",
    year: 1970,
    nation_code: "BR",
    flag: "🇧🇷",
    players: [
      { id: "pele_1970", name: "Pelé", position: "FWD", age_at_tournament: 29, overall: 99 },
      { id: "jairzinho_1970", name: "Jairzinho", position: "FWD", age_at_tournament: 25, overall: 91 },
      { id: "rivelino_1970", name: "Rivelino", position: "MID", age_at_tournament: 25, overall: 88 },
      { id: "tostao_1970", name: "Tostão", position: "FWD", age_at_tournament: 23, overall: 87 },
      { id: "gerson_1970", name: "Gérson", position: "MID", age_at_tournament: 27, overall: 85 },
      { id: "clodoaldo_1970", name: "Clodoaldo", position: "MID", age_at_tournament: 20, overall: 80 },
      { id: "carlos_alberto_1970", name: "Carlos Alberto", position: "DEF", age_at_tournament: 26, overall: 88 },
      { id: "everaldo_1970", name: "Everaldo", position: "DEF", age_at_tournament: 26, overall: 78 },
      { id: "piazza_1970", name: "Piazza", position: "DEF", age_at_tournament: 27, overall: 79 },
      { id: "brito_1970", name: "Brito", position: "DEF", age_at_tournament: 29, overall: 77 },
      { id: "felix_1970", name: "Félix", position: "GK", age_at_tournament: 32, overall: 80 },
    ],
  },
  brazil_1994: {
    team: "Brazil",
    year: 1994,
    nation_code: "BR",
    flag: "🇧🇷",
    players: [
      { id: "romario_1994", name: "Romário", position: "FWD", age_at_tournament: 28, overall: 95 },
      { id: "bebeto_1994", name: "Bebeto", position: "FWD", age_at_tournament: 30, overall: 88 },
      { id: "mazinho_1994", name: "Mazinho", position: "MID", age_at_tournament: 28, overall: 79 },
      { id: "mauro_silva_1994", name: "Mauro Silva", position: "MID", age_at_tournament: 26, overall: 78 },
      { id: "mauro_galvao_1994", name: "Mauro Galvão", position: "DEF", age_at_tournament: 30, overall: 76 },
      { id: "marcio_santos_1994", name: "Márcio Santos", position: "DEF", age_at_tournament: 26, overall: 80 },
      { id: "aldair_1994", name: "Aldair", position: "DEF", age_at_tournament: 27, overall: 82 },
      { id: "leonardo_1994", name: "Leonardo", position: "DEF", age_at_tournament: 25, overall: 83 },
      { id: "cafu_1994", name: "Cafu", position: "DEF", age_at_tournament: 24, overall: 82 },
      { id: "zinho_1994", name: "Zinho", position: "MID", age_at_tournament: 26, overall: 82 },
      { id: "rai_1994", name: "Raí", position: "MID", age_at_tournament: 27, overall: 83 },
      { id: "taffarel_1994", name: "Taffarel", position: "GK", age_at_tournament: 28, overall: 85 },
    ],
  },
  brazil_1982: {
    team: "Brazil",
    year: 1982,
    nation_code: "BR",
    flag: "🇧🇷",
    players: [
      { id: "zico_1982", name: "Zico", position: "MID", age_at_tournament: 29, overall: 94 },
      { id: "socrates_1982", name: "Sócrates", position: "MID", age_at_tournament: 28, overall: 90 },
      { id: "falcao_1982", name: "Falcão", position: "MID", age_at_tournament: 26, overall: 89 },
      { id: "serginho_1982", name: "Serginho", position: "FWD", age_at_tournament: 25, overall: 79 },
      { id: "eder_1982", name: "Éder", position: "FWD", age_at_tournament: 25, overall: 81 },
      { id: "junior_1982", name: "Júnior", position: "DEF", age_at_tournament: 26, overall: 83 },
      { id: "oscar_1982", name: "Oscar", position: "DEF", age_at_tournament: 26, overall: 78 },
      { id: "cerezo_1982", name: "Cerezo", position: "MID", age_at_tournament: 25, overall: 82 },
      { id: "luizinho_1982", name: "Luizinho", position: "DEF", age_at_tournament: 25, overall: 76 },
      { id: "leandro_1982", name: "Leandro", position: "DEF", age_at_tournament: 24, overall: 79 },
      { id: "waldir_peres_1982", name: "Waldir Peres", position: "GK", age_at_tournament: 31, overall: 78 },
    ],
  },
  brazil_2006: {
    team: "Brazil",
    year: 2006,
    nation_code: "BR",
    flag: "🇧🇷",
    players: [
      { id: "ronaldo_2006", name: "Ronaldo", position: "FWD", age_at_tournament: 29, overall: 90 },
      { id: "ronaldinho_2006", name: "Ronaldinho", position: "MID", age_at_tournament: 26, overall: 94 },
      { id: "adriano_2006", name: "Adriano", position: "FWD", age_at_tournament: 24, overall: 84 },
      { id: "kaka_2006", name: "Kaká", position: "MID", age_at_tournament: 24, overall: 91 },
      { id: "roberto_carlos_2006", name: "Roberto Carlos", position: "DEF", age_at_tournament: 33, overall: 83 },
      { id: "cafu_2006", name: "Cafu", position: "DEF", age_at_tournament: 36, overall: 79 },
      { id: "lucio_2006", name: "Lúcio", position: "DEF", age_at_tournament: 28, overall: 85 },
      { id: "juan_2006", name: "Juan", position: "DEF", age_at_tournament: 27, overall: 79 },
      { id: "gilberto_silva_2006", name: "Gilberto Silva", position: "MID", age_at_tournament: 29, overall: 80 },
      { id: "emerson_2006", name: "Emerson", position: "MID", age_at_tournament: 30, overall: 79 },
      { id: "dida_2006", name: "Dida", position: "GK", age_at_tournament: 32, overall: 84 },
    ],
  },
  brazil_2014: {
    team: "Brazil",
    year: 2014,
    nation_code: "BR",
    flag: "🇧🇷",
    players: [
      { id: "neymar_2014", name: "Neymar", position: "FWD", age_at_tournament: 22, overall: 91 },
      { id: "oscar_mid_2014", name: "Oscar", position: "MID", age_at_tournament: 22, overall: 81 },
      { id: "hulk_2014", name: "Hulk", position: "FWD", age_at_tournament: 27, overall: 81 },
      { id: "david_luiz_2014", name: "David Luiz", position: "DEF", age_at_tournament: 27, overall: 83 },
      { id: "thiago_silva_2014", name: "Thiago Silva", position: "DEF", age_at_tournament: 29, overall: 88 },
      { id: "dante_2014", name: "Dante", position: "DEF", age_at_tournament: 30, overall: 79 },
      { id: "maicon_2014", name: "Maicon", position: "DEF", age_at_tournament: 32, overall: 76 },
      { id: "marcelo_2014", name: "Marcelo", position: "DEF", age_at_tournament: 26, overall: 84 },
      { id: "paulinho_2014", name: "Paulinho", position: "MID", age_at_tournament: 25, overall: 78 },
      { id: "willian_2014", name: "Willian", position: "MID", age_at_tournament: 25, overall: 78 },
      { id: "julio_cesar_2014", name: "Júlio César", position: "GK", age_at_tournament: 34, overall: 80 },
    ],
  },
  argentina_1986: {
    team: "Argentina",
    year: 1986,
    nation_code: "AR",
    flag: "🇦🇷",
    players: [
      { id: "maradona_1986", name: "Diego Maradona", position: "MID", age_at_tournament: 25, overall: 99 },
      { id: "valdano_1986", name: "Jorge Valdano", position: "FWD", age_at_tournament: 29, overall: 82 },
      { id: "burruchaga_1986", name: "Jorge Burruchaga", position: "MID", age_at_tournament: 24, overall: 84 },
      { id: "enrique_1986", name: "Luis Enrique", position: "DEF", age_at_tournament: 26, overall: 79 },
      { id: "batista_1986", name: "Sergio Batista", position: "MID", age_at_tournament: 24, overall: 77 },
      { id: "giusti_1986", name: "Ricardo Giusti", position: "MID", age_at_tournament: 26, overall: 78 },
      { id: "olarticoechea_1986", name: "Julio Olarticoechea", position: "DEF", age_at_tournament: 26, overall: 79 },
      { id: "brown_1986", name: "José Brown", position: "DEF", age_at_tournament: 28, overall: 79 },
      { id: "cuciuffo_1986", name: "José Cuciuffo", position: "DEF", age_at_tournament: 24, overall: 76 },
      { id: "ruggeri_1986", name: "Oscar Ruggeri", position: "DEF", age_at_tournament: 24, overall: 82 },
      { id: "pumpido_1986", name: "Nery Pumpido", position: "GK", age_at_tournament: 27, overall: 82 },
    ],
  },
  argentina_2022: {
    team: "Argentina",
    year: 2022,
    nation_code: "AR",
    flag: "🇦🇷",
    players: [
      { id: "messi_2022", name: "Lionel Messi", position: "FWD", age_at_tournament: 35, overall: 98 },
      { id: "lautaro_2022", name: "Lautaro Martínez", position: "FWD", age_at_tournament: 25, overall: 87 },
      { id: "di_maria_2022", name: "Ángel Di María", position: "MID", age_at_tournament: 34, overall: 85 },
      { id: "de_paul_2022", name: "Rodrigo De Paul", position: "MID", age_at_tournament: 28, overall: 84 },
      { id: "mac_allister_2022", name: "Alexis Mac Allister", position: "MID", age_at_tournament: 24, overall: 82 },
      { id: "alvarez_2022", name: "Julián Álvarez", position: "FWD", age_at_tournament: 22, overall: 82 },
      { id: "otamendi_2022", name: "Nicolás Otamendi", position: "DEF", age_at_tournament: 34, overall: 82 },
      { id: "romero_2022", name: "Cristian Romero", position: "DEF", age_at_tournament: 24, overall: 83 },
      { id: "molina_2022", name: "Nahuel Molina", position: "DEF", age_at_tournament: 24, overall: 78 },
      { id: "tagliafico_2022", name: "Nicolás Tagliafico", position: "DEF", age_at_tournament: 30, overall: 79 },
      { id: "martinez_2022", name: "Emiliano Martínez", position: "GK", age_at_tournament: 30, overall: 87 },
    ],
  },
  argentina_1978: {
    team: "Argentina",
    year: 1978,
    nation_code: "AR",
    flag: "🇦🇷",
    players: [
      { id: "kempes_1978", name: "Mario Kempes", position: "FWD", age_at_tournament: 23, overall: 89 },
      { id: "ardiles_1978", name: "Osvaldo Ardiles", position: "MID", age_at_tournament: 25, overall: 84 },
      { id: "luque_1978", name: "Leopoldo Luque", position: "FWD", age_at_tournament: 26, overall: 80 },
      { id: "bertoni_1978", name: "Daniel Bertoni", position: "MID", age_at_tournament: 23, overall: 79 },
      { id: "galvan_1978", name: "Rubén Galván", position: "MID", age_at_tournament: 27, overall: 77 },
      { id: "passarella_1978", name: "Daniel Passarella", position: "DEF", age_at_tournament: 25, overall: 86 },
      { id: "tarantini_1978", name: "Alberto Tarantini", position: "DEF", age_at_tournament: 21, overall: 78 },
      { id: "fillol_1978", name: "Ubaldo Fillol", position: "GK", age_at_tournament: 27, overall: 86 },
    ],
  },
  argentina_2014: {
    team: "Argentina",
    year: 2014,
    nation_code: "AR",
    flag: "🇦🇷",
    players: [
      { id: "messi_2014", name: "Lionel Messi", position: "FWD", age_at_tournament: 26, overall: 97 },
      { id: "higuain_2014", name: "Gonzalo Higuaín", position: "FWD", age_at_tournament: 26, overall: 85 },
      { id: "di_maria_2014", name: "Ángel Di María", position: "MID", age_at_tournament: 26, overall: 87 },
      { id: "mascherano_2014", name: "Javier Mascherano", position: "MID", age_at_tournament: 30, overall: 87 },
      { id: "lavezzi_2014", name: "Ezequiel Lavezzi", position: "FWD", age_at_tournament: 28, overall: 82 },
      { id: "zabaleta_2014", name: "Pablo Zabaleta", position: "DEF", age_at_tournament: 29, overall: 81 },
      { id: "otamendi_2014", name: "Nicolás Otamendi", position: "DEF", age_at_tournament: 26, overall: 80 },
      { id: "garay_2014", name: "Ezequiel Garay", position: "DEF", age_at_tournament: 27, overall: 81 },
      { id: "rojo_2014", name: "Marcos Rojo", position: "DEF", age_at_tournament: 24, overall: 79 },
      { id: "romero_gk_2014", name: "Sergio Romero", position: "GK", age_at_tournament: 27, overall: 80 },
    ],
  },
  argentina_2006: {
    team: "Argentina",
    year: 2006,
    nation_code: "AR",
    flag: "🇦🇷",
    players: [
      { id: "messi_2006", name: "Lionel Messi", position: "FWD", age_at_tournament: 18, overall: 82 },
      { id: "riquelme_2006", name: "Juan Román Riquelme", position: "MID", age_at_tournament: 27, overall: 89 },
      { id: "crespo_2006", name: "Hernán Crespo", position: "FWD", age_at_tournament: 30, overall: 83 },
      { id: "saviola_2006", name: "Javier Saviola", position: "FWD", age_at_tournament: 24, overall: 79 },
      { id: "mascherano_2006", name: "Javier Mascherano", position: "MID", age_at_tournament: 22, overall: 80 },
      { id: "ayala_2006", name: "Roberto Ayala", position: "DEF", age_at_tournament: 33, overall: 83 },
      { id: "sorin_2006", name: "Juan Sorin", position: "DEF", age_at_tournament: 30, overall: 79 },
      { id: "abbondanzieri_2006", name: "Roberto Abbondanzieri", position: "GK", age_at_tournament: 33, overall: 80 },
    ],
  },
  france_1998: {
    team: "France",
    year: 1998,
    nation_code: "FR",
    flag: "🇫🇷",
    players: [
      { id: "zidane_1998", name: "Zinedine Zidane", position: "MID", age_at_tournament: 25, overall: 96 },
      { id: "desailly_1998", name: "Marcel Desailly", position: "DEF", age_at_tournament: 29, overall: 89 },
      { id: "blanc_1998", name: "Laurent Blanc", position: "DEF", age_at_tournament: 32, overall: 88 },
      { id: "thuram_1998", name: "Lilian Thuram", position: "DEF", age_at_tournament: 26, overall: 88 },
      { id: "deschamps_1998", name: "Didier Deschamps", position: "MID", age_at_tournament: 29, overall: 84 },
      { id: "vieira_1998", name: "Patrick Vieira", position: "MID", age_at_tournament: 21, overall: 84 },
      { id: "henry_1998", name: "Thierry Henry", position: "FWD", age_at_tournament: 20, overall: 82 },
      { id: "djorkaeff_1998", name: "Youri Djorkaeff", position: "MID", age_at_tournament: 30, overall: 83 },
      { id: "lizarazu_1998", name: "Bixente Lizarazu", position: "DEF", age_at_tournament: 27, overall: 83 },
      { id: "dugarry_1998", name: "Christophe Dugarry", position: "FWD", age_at_tournament: 26, overall: 78 },
      { id: "barthez_1998", name: "Fabien Barthez", position: "GK", age_at_tournament: 26, overall: 89 },
    ],
  },
  france_2018: {
    team: "France",
    year: 2018,
    nation_code: "FR",
    flag: "🇫🇷",
    players: [
      { id: "mbappe_2018", name: "Kylian Mbappé", position: "FWD", age_at_tournament: 19, overall: 90 },
      { id: "griezmann_2018", name: "Antoine Griezmann", position: "FWD", age_at_tournament: 27, overall: 89 },
      { id: "pogba_2018", name: "Paul Pogba", position: "MID", age_at_tournament: 25, overall: 87 },
      { id: "kante_2018", name: "N'Golo Kanté", position: "MID", age_at_tournament: 27, overall: 88 },
      { id: "varane_2018", name: "Raphaël Varane", position: "DEF", age_at_tournament: 25, overall: 86 },
      { id: "umtiti_2018", name: "Samuel Umtiti", position: "DEF", age_at_tournament: 24, overall: 83 },
      { id: "pavard_2018", name: "Benjamin Pavard", position: "DEF", age_at_tournament: 22, overall: 79 },
      { id: "hernandez_2018", name: "Lucas Hernández", position: "DEF", age_at_tournament: 22, overall: 80 },
      { id: "matuidi_2018", name: "Blaise Matuidi", position: "MID", age_at_tournament: 31, overall: 82 },
      { id: "giroud_2018", name: "Olivier Giroud", position: "FWD", age_at_tournament: 31, overall: 81 },
      { id: "lloris_2018", name: "Hugo Lloris", position: "GK", age_at_tournament: 31, overall: 87 },
    ],
  },
  france_2006: {
    team: "France",
    year: 2006,
    nation_code: "FR",
    flag: "🇫🇷",
    players: [
      { id: "zidane_2006", name: "Zinedine Zidane", position: "MID", age_at_tournament: 33, overall: 94 },
      { id: "henry_2006", name: "Thierry Henry", position: "FWD", age_at_tournament: 28, overall: 91 },
      { id: "ribery_2006", name: "Franck Ribéry", position: "MID", age_at_tournament: 23, overall: 79 },
      { id: "malouda_2006", name: "Florent Malouda", position: "MID", age_at_tournament: 26, overall: 78 },
      { id: "vieira_2006", name: "Patrick Vieira", position: "MID", age_at_tournament: 29, overall: 87 },
      { id: "makelele_2006", name: "Claude Makélélé", position: "MID", age_at_tournament: 33, overall: 84 },
      { id: "thuram_2006", name: "Lilian Thuram", position: "DEF", age_at_tournament: 34, overall: 82 },
      { id: "sagnol_2006", name: "Willy Sagnol", position: "DEF", age_at_tournament: 29, overall: 80 },
      { id: "abidal_2006", name: "Éric Abidal", position: "DEF", age_at_tournament: 26, overall: 80 },
      { id: "gallas_2006", name: "William Gallas", position: "DEF", age_at_tournament: 29, overall: 82 },
      { id: "barthez_2006", name: "Fabien Barthez", position: "GK", age_at_tournament: 34, overall: 83 },
    ],
  },
  france_2022: {
    team: "France",
    year: 2022,
    nation_code: "FR",
    flag: "🇫🇷",
    players: [
      { id: "mbappe_2022", name: "Kylian Mbappé", position: "FWD", age_at_tournament: 23, overall: 93 },
      { id: "griezmann_2022", name: "Antoine Griezmann", position: "MID", age_at_tournament: 31, overall: 87 },
      { id: "giroud_2022", name: "Olivier Giroud", position: "FWD", age_at_tournament: 36, overall: 82 },
      { id: "tchouameni_2022", name: "Aurélien Tchouaméni", position: "MID", age_at_tournament: 22, overall: 83 },
      { id: "rabiot_2022", name: "Adrien Rabiot", position: "MID", age_at_tournament: 27, overall: 82 },
      { id: "varane_2022", name: "Raphaël Varane", position: "DEF", age_at_tournament: 29, overall: 84 },
      { id: "upamecano_2022", name: "Dayot Upamecano", position: "DEF", age_at_tournament: 24, overall: 81 },
      { id: "theo_2022", name: "Theo Hernández", position: "DEF", age_at_tournament: 24, overall: 83 },
      { id: "kounde_2022", name: "Jules Koundé", position: "DEF", age_at_tournament: 24, overall: 81 },
      { id: "dembele_2022", name: "Ousmane Dembélé", position: "MID", age_at_tournament: 25, overall: 82 },
      { id: "lloris_2022", name: "Hugo Lloris", position: "GK", age_at_tournament: 35, overall: 83 },
    ],
  },
  germany_2014: {
    team: "Germany",
    year: 2014,
    nation_code: "DE",
    flag: "🇩🇪",
    players: [
      { id: "neuer_2014", name: "Manuel Neuer", position: "GK", age_at_tournament: 28, overall: 94 },
      { id: "muller_2014", name: "Thomas Müller", position: "FWD", age_at_tournament: 24, overall: 87 },
      { id: "klose_2014", name: "Miroslav Klose", position: "FWD", age_at_tournament: 36, overall: 84 },
      { id: "ozil_2014", name: "Mesut Özil", position: "MID", age_at_tournament: 25, overall: 87 },
      { id: "schweinsteiger_2014", name: "Bastian Schweinsteiger", position: "MID", age_at_tournament: 29, overall: 87 },
      { id: "lahm_2014", name: "Philipp Lahm", position: "DEF", age_at_tournament: 30, overall: 88 },
      { id: "hummels_2014", name: "Mats Hummels", position: "DEF", age_at_tournament: 25, overall: 85 },
      { id: "boateng_2014", name: "Jérôme Boateng", position: "DEF", age_at_tournament: 25, overall: 84 },
      { id: "howedes_2014", name: "Benedikt Höwedes", position: "DEF", age_at_tournament: 26, overall: 79 },
      { id: "kroos_2014", name: "Toni Kroos", position: "MID", age_at_tournament: 24, overall: 88 },
      { id: "khedira_2014", name: "Sami Khedira", position: "MID", age_at_tournament: 27, overall: 83 },
    ],
  },
  germany_1974: {
    team: "Germany",
    year: 1974,
    nation_code: "DE",
    flag: "🇩🇪",
    players: [
      { id: "beckenbauer_1974", name: "Franz Beckenbauer", position: "DEF", age_at_tournament: 28, overall: 97 },
      { id: "muller_g_1974", name: "Gerd Müller", position: "FWD", age_at_tournament: 28, overall: 96 },
      { id: "breitner_1974", name: "Paul Breitner", position: "DEF", age_at_tournament: 22, overall: 85 },
      { id: "maier_1974", name: "Sepp Maier", position: "GK", age_at_tournament: 30, overall: 90 },
      { id: "overath_1974", name: "Wolfgang Overath", position: "MID", age_at_tournament: 30, overall: 84 },
      { id: "netzer_1974", name: "Günter Netzer", position: "MID", age_at_tournament: 29, overall: 85 },
      { id: "grabowski_1974", name: "Jürgen Grabowski", position: "MID", age_at_tournament: 28, overall: 82 },
      { id: "schwarzenbeck_1974", name: "Georg Schwarzenbeck", position: "DEF", age_at_tournament: 26, overall: 80 },
    ],
  },
  germany_1990: {
    team: "Germany",
    year: 1990,
    nation_code: "DE",
    flag: "🇩🇪",
    players: [
      { id: "matthaeus_1990", name: "Lothar Matthäus", position: "MID", age_at_tournament: 29, overall: 96 },
      { id: "klinsmann_1990", name: "Jürgen Klinsmann", position: "FWD", age_at_tournament: 25, overall: 86 },
      { id: "voller_1990", name: "Rudi Völler", position: "FWD", age_at_tournament: 29, overall: 85 },
      { id: "brehme_1990", name: "Andreas Brehme", position: "DEF", age_at_tournament: 29, overall: 86 },
      { id: "kohler_1990", name: "Jürgen Kohler", position: "DEF", age_at_tournament: 24, overall: 82 },
      { id: "buchwald_1990", name: "Guido Buchwald", position: "DEF", age_at_tournament: 28, overall: 80 },
      { id: "illgner_1990", name: "Bodo Illgner", position: "GK", age_at_tournament: 24, overall: 83 },
    ],
  },
  germany_2010: {
    team: "Germany",
    year: 2010,
    nation_code: "DE",
    flag: "🇩🇪",
    players: [
      { id: "muller_2010", name: "Thomas Müller", position: "FWD", age_at_tournament: 20, overall: 82 },
      { id: "klose_2010", name: "Miroslav Klose", position: "FWD", age_at_tournament: 32, overall: 83 },
      { id: "ozil_2010", name: "Mesut Özil", position: "MID", age_at_tournament: 21, overall: 83 },
      { id: "schweinsteiger_2010", name: "Bastian Schweinsteiger", position: "MID", age_at_tournament: 25, overall: 83 },
      { id: "lahm_2010", name: "Philipp Lahm", position: "DEF", age_at_tournament: 26, overall: 85 },
      { id: "friedrich_2010", name: "Arne Friedrich", position: "DEF", age_at_tournament: 31, overall: 78 },
      { id: "mertesacker_2010", name: "Per Mertesacker", position: "DEF", age_at_tournament: 25, overall: 80 },
      { id: "neuer_2010", name: "Manuel Neuer", position: "GK", age_at_tournament: 24, overall: 86 },
    ],
  },
  germany_2006: {
    team: "Germany",
    year: 2006,
    nation_code: "DE",
    flag: "🇩🇪",
    players: [
      { id: "ballack_2006", name: "Michael Ballack", position: "MID", age_at_tournament: 29, overall: 89 },
      { id: "klose_2006", name: "Miroslav Klose", position: "FWD", age_at_tournament: 28, overall: 84 },
      { id: "podolski_2006", name: "Lukas Podolski", position: "FWD", age_at_tournament: 21, overall: 79 },
      { id: "frings_2006", name: "Torsten Frings", position: "MID", age_at_tournament: 29, overall: 79 },
      { id: "lahm_2006", name: "Philipp Lahm", position: "DEF", age_at_tournament: 22, overall: 80 },
      { id: "lehmann_2006", name: "Jens Lehmann", position: "GK", age_at_tournament: 36, overall: 83 },
    ],
  },
  italy_2006: {
    team: "Italy",
    year: 2006,
    nation_code: "IT",
    flag: "🇮🇹",
    players: [
      { id: "pirlo_2006", name: "Andrea Pirlo", position: "MID", age_at_tournament: 27, overall: 91 },
      { id: "totti_2006", name: "Francesco Totti", position: "MID", age_at_tournament: 29, overall: 88 },
      { id: "cannavaro_2006", name: "Fabio Cannavaro", position: "DEF", age_at_tournament: 32, overall: 93 },
      { id: "buffon_2006", name: "Gianluigi Buffon", position: "GK", age_at_tournament: 28, overall: 93 },
      { id: "gattuso_2006", name: "Gennaro Gattuso", position: "MID", age_at_tournament: 28, overall: 84 },
      { id: "toni_2006", name: "Luca Toni", position: "FWD", age_at_tournament: 29, overall: 84 },
      { id: "materazzi_2006", name: "Marco Materazzi", position: "DEF", age_at_tournament: 32, overall: 80 },
      { id: "nesta_2006", name: "Alessandro Nesta", position: "DEF", age_at_tournament: 30, overall: 90 },
      { id: "zambrotta_2006", name: "Gianluca Zambrotta", position: "DEF", age_at_tournament: 29, overall: 83 },
      { id: "grosso_2006", name: "Fabio Grosso", position: "DEF", age_at_tournament: 28, overall: 78 },
      { id: "del_piero_2006", name: "Alessandro Del Piero", position: "FWD", age_at_tournament: 31, overall: 87 },
      { id: "inzaghi_2006", name: "Filippo Inzaghi", position: "FWD", age_at_tournament: 32, overall: 83 },
      { id: "camoranesi_2006", name: "Mauro Camoranesi", position: "MID", age_at_tournament: 29, overall: 79 },
    ],
  },
  italy_1982: {
    team: "Italy",
    year: 1982,
    nation_code: "IT",
    flag: "🇮🇹",
    players: [
      { id: "rossi_1982", name: "Paolo Rossi", position: "FWD", age_at_tournament: 25, overall: 91 },
      { id: "zoff_1982", name: "Dino Zoff", position: "GK", age_at_tournament: 40, overall: 89 },
      { id: "tardelli_1982", name: "Marco Tardelli", position: "MID", age_at_tournament: 27, overall: 85 },
      { id: "scirea_1982", name: "Gaetano Scirea", position: "DEF", age_at_tournament: 29, overall: 86 },
      { id: "gentile_1982", name: "Claudio Gentile", position: "DEF", age_at_tournament: 29, overall: 82 },
      { id: "antognoni_1982", name: "Giancarlo Antognoni", position: "MID", age_at_tournament: 28, overall: 84 },
      { id: "cabrini_1982", name: "Antonio Cabrini", position: "DEF", age_at_tournament: 24, overall: 82 },
      { id: "conti_1982", name: "Bruno Conti", position: "MID", age_at_tournament: 26, overall: 81 },
    ],
  },
  italy_1970: {
    team: "Italy",
    year: 1970,
    nation_code: "IT",
    flag: "🇮🇹",
    players: [
      { id: "riva_1970", name: "Gigi Riva", position: "FWD", age_at_tournament: 25, overall: 91 },
      { id: "mazzola_1970", name: "Sandro Mazzola", position: "MID", age_at_tournament: 28, overall: 86 },
      { id: "boninsegna_1970", name: "Roberto Boninsegna", position: "FWD", age_at_tournament: 25, overall: 82 },
      { id: "facchetti_1970", name: "Giacinto Facchetti", position: "DEF", age_at_tournament: 27, overall: 88 },
      { id: "burgnich_1970", name: "Tarcisio Burgnich", position: "DEF", age_at_tournament: 30, overall: 82 },
      { id: "albertosi_1970", name: "Enrico Albertosi", position: "GK", age_at_tournament: 31, overall: 81 },
    ],
  },
  italy_1994: {
    team: "Italy",
    year: 1994,
    nation_code: "IT",
    flag: "🇮🇹",
    players: [
      { id: "baggio_1994", name: "Roberto Baggio", position: "FWD", age_at_tournament: 27, overall: 95 },
      { id: "maldini_1994", name: "Paolo Maldini", position: "DEF", age_at_tournament: 25, overall: 93 },
      { id: "baresi_1994", name: "Franco Baresi", position: "DEF", age_at_tournament: 34, overall: 90 },
      { id: "costacurta_1994", name: "Alessandro Costacurta", position: "DEF", age_at_tournament: 30, overall: 85 },
      { id: "albertini_1994", name: "Demetrio Albertini", position: "MID", age_at_tournament: 23, overall: 81 },
      { id: "signori_1994", name: "Giuseppe Signori", position: "FWD", age_at_tournament: 26, overall: 83 },
      { id: "massaro_1994", name: "Daniele Massaro", position: "FWD", age_at_tournament: 33, overall: 79 },
      { id: "pagliuca_1994", name: "Gianluca Pagliuca", position: "GK", age_at_tournament: 28, overall: 83 },
    ],
  },
  spain_2010: {
    team: "Spain",
    year: 2010,
    nation_code: "ES",
    flag: "🇪🇸",
    players: [
      { id: "xavi_2010", name: "Xavi Hernández", position: "MID", age_at_tournament: 30, overall: 94 },
      { id: "iniesta_2010", name: "Andrés Iniesta", position: "MID", age_at_tournament: 26, overall: 92 },
      { id: "david_villa_2010", name: "David Villa", position: "FWD", age_at_tournament: 28, overall: 89 },
      { id: "busquets_2010", name: "Sergio Busquets", position: "MID", age_at_tournament: 21, overall: 85 },
      { id: "puyol_2010", name: "Carles Puyol", position: "DEF", age_at_tournament: 32, overall: 88 },
      { id: "pique_2010", name: "Gerard Piqué", position: "DEF", age_at_tournament: 23, overall: 84 },
      { id: "ramos_2010", name: "Sergio Ramos", position: "DEF", age_at_tournament: 24, overall: 85 },
      { id: "capdevila_2010", name: "Joan Capdevila", position: "DEF", age_at_tournament: 33, overall: 79 },
      { id: "alonso_2010", name: "Xabi Alonso", position: "MID", age_at_tournament: 28, overall: 87 },
      { id: "torres_2010", name: "Fernando Torres", position: "FWD", age_at_tournament: 26, overall: 86 },
      { id: "casillas_2010", name: "Iker Casillas", position: "GK", age_at_tournament: 29, overall: 93 },
    ],
  },
  spain_2014: {
    team: "Spain",
    year: 2014,
    nation_code: "ES",
    flag: "🇪🇸",
    players: [
      { id: "xavi_2014", name: "Xavi Hernández", position: "MID", age_at_tournament: 34, overall: 89 },
      { id: "iniesta_2014", name: "Andrés Iniesta", position: "MID", age_at_tournament: 30, overall: 90 },
      { id: "david_villa_2014", name: "David Villa", position: "FWD", age_at_tournament: 32, overall: 84 },
      { id: "busquets_2014", name: "Sergio Busquets", position: "MID", age_at_tournament: 25, overall: 87 },
      { id: "ramos_2014", name: "Sergio Ramos", position: "DEF", age_at_tournament: 28, overall: 87 },
      { id: "pique_2014", name: "Gerard Piqué", position: "DEF", age_at_tournament: 27, overall: 85 },
      { id: "jordi_alba_2014", name: "Jordi Alba", position: "DEF", age_at_tournament: 25, overall: 83 },
      { id: "casillas_2014", name: "Iker Casillas", position: "GK", age_at_tournament: 33, overall: 87 },
    ],
  },
  spain_2022: {
    team: "Spain",
    year: 2022,
    nation_code: "ES",
    flag: "🇪🇸",
    players: [
      { id: "pedri_2022", name: "Pedri", position: "MID", age_at_tournament: 20, overall: 85 },
      { id: "gavi_2022", name: "Gavi", position: "MID", age_at_tournament: 18, overall: 83 },
      { id: "ferran_2022", name: "Ferran Torres", position: "FWD", age_at_tournament: 22, overall: 79 },
      { id: "morata_2022", name: "Álvaro Morata", position: "FWD", age_at_tournament: 30, overall: 80 },
      { id: "asensio_2022", name: "Marco Asensio", position: "MID", age_at_tournament: 26, overall: 79 },
      { id: "rodri_2022", name: "Rodri", position: "MID", age_at_tournament: 26, overall: 87 },
      { id: "eric_garcia_2022", name: "Éric García", position: "DEF", age_at_tournament: 21, overall: 78 },
      { id: "laporte_2022", name: "Aymeric Laporte", position: "DEF", age_at_tournament: 28, overall: 83 },
      { id: "alba_2022", name: "Jordi Alba", position: "DEF", age_at_tournament: 33, overall: 79 },
      { id: "azpilicueta_2022", name: "César Azpilicueta", position: "DEF", age_at_tournament: 33, overall: 78 },
      { id: "unai_simon_2022", name: "Unai Simón", position: "GK", age_at_tournament: 25, overall: 82 },
    ],
  },
  netherlands_1974: {
    team: "Netherlands",
    year: 1974,
    nation_code: "NL",
    flag: "🇳🇱",
    players: [
      { id: "cruyff_1974", name: "Johan Cruyff", position: "FWD", age_at_tournament: 27, overall: 99 },
      { id: "neeskens_1974", name: "Johan Neeskens", position: "MID", age_at_tournament: 22, overall: 88 },
      { id: "rep_1974", name: "Johnny Rep", position: "FWD", age_at_tournament: 22, overall: 82 },
      { id: "rensenbrink_1974", name: "Rob Rensenbrink", position: "FWD", age_at_tournament: 24, overall: 83 },
      { id: "krol_1974", name: "Ruud Krol", position: "DEF", age_at_tournament: 23, overall: 83 },
      { id: "haan_1974", name: "Arie Haan", position: "MID", age_at_tournament: 23, overall: 81 },
      { id: "jansen_1974", name: "Wim Jansen", position: "MID", age_at_tournament: 26, overall: 80 },
      { id: "jongbloed_1974", name: "Jan Jongbloed", position: "GK", age_at_tournament: 33, overall: 80 },
    ],
  },
  netherlands_2010: {
    team: "Netherlands",
    year: 2010,
    nation_code: "NL",
    flag: "🇳🇱",
    players: [
      { id: "robben_2010", name: "Arjen Robben", position: "MID", age_at_tournament: 26, overall: 88 },
      { id: "van_persie_2010", name: "Robin van Persie", position: "FWD", age_at_tournament: 26, overall: 87 },
      { id: "sneijder_2010", name: "Wesley Sneijder", position: "MID", age_at_tournament: 26, overall: 90 },
      { id: "van_bommel_2010", name: "Mark van Bommel", position: "MID", age_at_tournament: 33, overall: 82 },
      { id: "de_jong_2010", name: "Nigel de Jong", position: "MID", age_at_tournament: 25, overall: 80 },
      { id: "van_bronckhorst_2010", name: "Giovanni van Bronckhorst", position: "DEF", age_at_tournament: 35, overall: 80 },
      { id: "heitinga_2010", name: "John Heitinga", position: "DEF", age_at_tournament: 26, overall: 79 },
      { id: "mathijsen_2010", name: "Joris Mathijsen", position: "DEF", age_at_tournament: 29, overall: 78 },
      { id: "stekelenburg_2010", name: "Maarten Stekelenburg", position: "GK", age_at_tournament: 27, overall: 80 },
    ],
  },
  netherlands_1978: {
    team: "Netherlands",
    year: 1978,
    nation_code: "NL",
    flag: "🇳🇱",
    players: [
      { id: "rensenbrink_1978", name: "Rob Rensenbrink", position: "FWD", age_at_tournament: 28, overall: 86 },
      { id: "rep_1978", name: "Johnny Rep", position: "FWD", age_at_tournament: 26, overall: 83 },
      { id: "neeskens_1978", name: "Johan Neeskens", position: "MID", age_at_tournament: 26, overall: 85 },
      { id: "krol_1978", name: "Ruud Krol", position: "DEF", age_at_tournament: 27, overall: 84 },
      { id: "haan_1978", name: "Arie Haan", position: "MID", age_at_tournament: 27, overall: 82 },
      { id: "jansen_1978", name: "Wim Jansen", position: "MID", age_at_tournament: 30, overall: 79 },
      { id: "poortvliet_1978", name: "Jan Poortvliet", position: "DEF", age_at_tournament: 24, overall: 78 },
      { id: "jongbloed_1978", name: "Jan Jongbloed", position: "GK", age_at_tournament: 37, overall: 78 },
    ],
  },
  england_1966: {
    team: "England",
    year: 1966,
    nation_code: "GB-ENG",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    players: [
      { id: "charlton_1966", name: "Bobby Charlton", position: "MID", age_at_tournament: 28, overall: 93 },
      { id: "moore_1966", name: "Bobby Moore", position: "DEF", age_at_tournament: 25, overall: 92 },
      { id: "geoff_hurst_1966", name: "Geoff Hurst", position: "FWD", age_at_tournament: 24, overall: 86 },
      { id: "peters_1966", name: "Martin Peters", position: "MID", age_at_tournament: 22, overall: 83 },
      { id: "ball_1966", name: "Alan Ball", position: "MID", age_at_tournament: 21, overall: 81 },
      { id: "stiles_1966", name: "Nobby Stiles", position: "MID", age_at_tournament: 23, overall: 79 },
      { id: "cohen_1966", name: "George Cohen", position: "DEF", age_at_tournament: 26, overall: 80 },
      { id: "jack_charlton_1966", name: "Jack Charlton", position: "DEF", age_at_tournament: 30, overall: 79 },
      { id: "wilson_1966", name: "Ray Wilson", position: "DEF", age_at_tournament: 31, overall: 80 },
      { id: "greaves_1966", name: "Jimmy Greaves", position: "FWD", age_at_tournament: 26, overall: 84 },
      { id: "banks_1966", name: "Gordon Banks", position: "GK", age_at_tournament: 27, overall: 91 },
    ],
  },
  england_1990: {
    team: "England",
    year: 1990,
    nation_code: "GB-ENG",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    players: [
      { id: "lineker_1990", name: "Gary Lineker", position: "FWD", age_at_tournament: 29, overall: 87 },
      { id: "gascoigne_1990", name: "Paul Gascoigne", position: "MID", age_at_tournament: 23, overall: 87 },
      { id: "waddle_1990", name: "Chris Waddle", position: "MID", age_at_tournament: 29, overall: 82 },
      { id: "beardsley_1990", name: "Peter Beardsley", position: "MID", age_at_tournament: 29, overall: 82 },
      { id: "shilton_1990", name: "Peter Shilton", position: "GK", age_at_tournament: 40, overall: 83 },
      { id: "wright_1990", name: "Mark Wright", position: "DEF", age_at_tournament: 27, overall: 79 },
      { id: "butcher_1990", name: "Terry Butcher", position: "DEF", age_at_tournament: 31, overall: 79 },
    ],
  },
  england_2018: {
    team: "England",
    year: 2018,
    nation_code: "GB-ENG",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    players: [
      { id: "kane_2018", name: "Harry Kane", position: "FWD", age_at_tournament: 24, overall: 86 },
      { id: "sterling_2018", name: "Raheem Sterling", position: "MID", age_at_tournament: 23, overall: 83 },
      { id: "trippier_2018", name: "Kieran Trippier", position: "DEF", age_at_tournament: 27, overall: 79 },
      { id: "pickford_2018", name: "Jordan Pickford", position: "GK", age_at_tournament: 24, overall: 79 },
      { id: "maguire_2018", name: "Harry Maguire", position: "DEF", age_at_tournament: 25, overall: 78 },
      { id: "henderson_2018", name: "Jordan Henderson", position: "MID", age_at_tournament: 27, overall: 80 },
      { id: "dele_2018", name: "Dele Alli", position: "MID", age_at_tournament: 22, overall: 81 },
    ],
  },
  portugal_2006: {
    team: "Portugal",
    year: 2006,
    nation_code: "PT",
    flag: "🇵🇹",
    players: [
      { id: "ronaldo_cr_2006", name: "Cristiano Ronaldo", position: "FWD", age_at_tournament: 21, overall: 83 },
      { id: "figo_2006", name: "Luís Figo", position: "MID", age_at_tournament: 33, overall: 87 },
      { id: "deco_2006", name: "Deco", position: "MID", age_at_tournament: 28, overall: 87 },
      { id: "pauleta_2006", name: "Pauleta", position: "FWD", age_at_tournament: 33, overall: 79 },
      { id: "maniche_2006", name: "Maniche", position: "MID", age_at_tournament: 29, overall: 79 },
      { id: "carvalho_2006", name: "Ricardo Carvalho", position: "DEF", age_at_tournament: 28, overall: 84 },
      { id: "nuno_valente_2006", name: "Nuno Valente", position: "DEF", age_at_tournament: 30, overall: 78 },
      { id: "tiago_2006", name: "Tiago", position: "MID", age_at_tournament: 25, overall: 79 },
      { id: "ricardo_gk_2006", name: "Ricardo", position: "GK", age_at_tournament: 31, overall: 80 },
    ],
  },
  portugal_2022: {
    team: "Portugal",
    year: 2022,
    nation_code: "PT",
    flag: "🇵🇹",
    players: [
      { id: "ronaldo_cr_2022", name: "Cristiano Ronaldo", position: "FWD", age_at_tournament: 37, overall: 90 },
      { id: "bernardo_2022", name: "Bernardo Silva", position: "MID", age_at_tournament: 28, overall: 88 },
      { id: "bruno_2022", name: "Bruno Fernandes", position: "MID", age_at_tournament: 28, overall: 86 },
      { id: "joao_felix_2022", name: "João Félix", position: "FWD", age_at_tournament: 23, overall: 83 },
      { id: "cancelo_2022", name: "João Cancelo", position: "DEF", age_at_tournament: 28, overall: 86 },
      { id: "dias_2022", name: "Rúben Dias", position: "DEF", age_at_tournament: 25, overall: 87 },
      { id: "costa_2022", name: "Pepe", position: "DEF", age_at_tournament: 39, overall: 80 },
      { id: "guerreiro_2022", name: "Raphaël Guerreiro", position: "DEF", age_at_tournament: 28, overall: 81 },
      { id: "diogo_j_2022", name: "Diogo Jota", position: "FWD", age_at_tournament: 26, overall: 82 },
      { id: "patricio_2022", name: "Rui Patrício", position: "GK", age_at_tournament: 34, overall: 82 },
    ],
  },
  croatia_2018: {
    team: "Croatia",
    year: 2018,
    nation_code: "HR",
    flag: "🇭🇷",
    players: [
      { id: "modric_2018", name: "Luka Modrić", position: "MID", age_at_tournament: 32, overall: 93 },
      { id: "rakitic_2018", name: "Ivan Rakitić", position: "MID", age_at_tournament: 30, overall: 87 },
      { id: "perisic_2018", name: "Ivan Perišić", position: "MID", age_at_tournament: 29, overall: 84 },
      { id: "mandzo_2018", name: "Mario Mandžukić", position: "FWD", age_at_tournament: 32, overall: 82 },
      { id: "vida_2018", name: "Domagoj Vida", position: "DEF", age_at_tournament: 29, overall: 79 },
      { id: "lovren_2018", name: "Dejan Lovren", position: "DEF", age_at_tournament: 28, overall: 81 },
      { id: "strinic_2018", name: "Ivan Strinić", position: "DEF", age_at_tournament: 30, overall: 76 },
      { id: "vrsaljko_2018", name: "Šime Vrsaljko", position: "DEF", age_at_tournament: 26, overall: 78 },
      { id: "brozovic_2018", name: "Marcelo Brozović", position: "MID", age_at_tournament: 25, overall: 83 },
      { id: "kramaric_2018", name: "Andrej Kramarić", position: "FWD", age_at_tournament: 26, overall: 81 },
      { id: "subasic_2018", name: "Danijel Subašić", position: "GK", age_at_tournament: 33, overall: 82 },
    ],
  },
  croatia_2022: {
    team: "Croatia",
    year: 2022,
    nation_code: "HR",
    flag: "🇭🇷",
    players: [
      { id: "modric_2022", name: "Luka Modrić", position: "MID", age_at_tournament: 37, overall: 89 },
      { id: "gvardiol_2022", name: "Joško Gvardiol", position: "DEF", age_at_tournament: 20, overall: 82 },
      { id: "kramaric_2022", name: "Andrej Kramarić", position: "FWD", age_at_tournament: 31, overall: 80 },
      { id: "kovacic_2022", name: "Mateo Kovačić", position: "MID", age_at_tournament: 28, overall: 84 },
      { id: "perisic_2022", name: "Ivan Perišić", position: "MID", age_at_tournament: 33, overall: 80 },
      { id: "livakovic_2022", name: "Dominik Livaković", position: "GK", age_at_tournament: 27, overall: 82 },
    ],
  },
  belgium_2018: {
    team: "Belgium",
    year: 2018,
    nation_code: "BE",
    flag: "🇧🇪",
    players: [
      { id: "de_bruyne_2018", name: "Kevin De Bruyne", position: "MID", age_at_tournament: 27, overall: 91 },
      { id: "hazard_2018", name: "Eden Hazard", position: "MID", age_at_tournament: 27, overall: 90 },
      { id: "lukaku_2018", name: "Romelu Lukaku", position: "FWD", age_at_tournament: 25, overall: 87 },
      { id: "mertens_2018", name: "Dries Mertens", position: "FWD", age_at_tournament: 31, overall: 84 },
      { id: "carrasco_2018", name: "Yannick Carrasco", position: "MID", age_at_tournament: 24, overall: 82 },
      { id: "witsel_2018", name: "Axel Witsel", position: "MID", age_at_tournament: 29, overall: 83 },
      { id: "kompany_2018", name: "Vincent Kompany", position: "DEF", age_at_tournament: 32, overall: 84 },
      { id: "alderweireld_2018", name: "Toby Alderweireld", position: "DEF", age_at_tournament: 29, overall: 85 },
      { id: "vertonghen_2018", name: "Jan Vertonghen", position: "DEF", age_at_tournament: 31, overall: 83 },
      { id: "meunier_2018", name: "Thomas Meunier", position: "DEF", age_at_tournament: 26, overall: 79 },
      { id: "courtois_2018", name: "Thibaut Courtois", position: "GK", age_at_tournament: 26, overall: 89 },
    ],
  },
  belgium_2022: {
    team: "Belgium",
    year: 2022,
    nation_code: "BE",
    flag: "🇧🇪",
    players: [
      { id: "de_bruyne_2022", name: "Kevin De Bruyne", position: "MID", age_at_tournament: 31, overall: 90 },
      { id: "lukaku_2022", name: "Romelu Lukaku", position: "FWD", age_at_tournament: 29, overall: 85 },
      { id: "hazard_2022", name: "Eden Hazard", position: "MID", age_at_tournament: 31, overall: 82 },
      { id: "trossard_2022", name: "Leandro Trossard", position: "MID", age_at_tournament: 27, overall: 80 },
      { id: "courtois_2022", name: "Thibaut Courtois", position: "GK", age_at_tournament: 30, overall: 90 },
      { id: "alderweireld_2022", name: "Toby Alderweireld", position: "DEF", age_at_tournament: 33, overall: 81 },
      { id: "vertonghen_2022", name: "Jan Vertonghen", position: "DEF", age_at_tournament: 35, overall: 79 },
    ],
  },
  cameroon_1990: {
    team: "Cameroon",
    year: 1990,
    nation_code: "CM",
    flag: "🇨🇲",
    players: [
      { id: "milla_1990", name: "Roger Milla", position: "FWD", age_at_tournament: 38, overall: 82 },
      { id: "omam_biyik_1990", name: "François Omam-Biyik", position: "FWD", age_at_tournament: 23, overall: 76 },
      { id: "maboang_1990", name: "Gaston Maboang", position: "MID", age_at_tournament: 25, overall: 72 },
      { id: "nkono_1990", name: "Thomas N'Kono", position: "GK", age_at_tournament: 34, overall: 79 },
      { id: "pagal_1990", name: "André Kana-Biyik", position: "DEF", age_at_tournament: 22, overall: 72 },
    ],
  },
  senegal_2002: {
    team: "Senegal",
    year: 2002,
    nation_code: "SN",
    flag: "🇸🇳",
    players: [
      { id: "diouf_2002", name: "El-Hadji Diouf", position: "FWD", age_at_tournament: 21, overall: 80 },
      { id: "diop_2002", name: "Papa Bouba Diop", position: "MID", age_at_tournament: 23, overall: 77 },
      { id: "diatta_2002", name: "Lamine Diatta", position: "DEF", age_at_tournament: 25, overall: 74 },
      { id: "coly_2002", name: "Ferdinand Coly", position: "DEF", age_at_tournament: 28, overall: 74 },
      { id: "sylva_2002", name: "Tony Sylva", position: "GK", age_at_tournament: 27, overall: 76 },
    ],
  },
  morocco_2022: {
    team: "Morocco",
    year: 2022,
    nation_code: "MA",
    flag: "🇲🇦",
    players: [
      { id: "ziyech_2022", name: "Hakim Ziyech", position: "MID", age_at_tournament: 29, overall: 82 },
      { id: "en_nesyri_2022", name: "Youssef En-Nesyri", position: "FWD", age_at_tournament: 25, overall: 79 },
      { id: "hakimi_2022", name: "Achraf Hakimi", position: "DEF", age_at_tournament: 24, overall: 84 },
      { id: "amrabat_2022", name: "Sofyan Amrabat", position: "MID", age_at_tournament: 26, overall: 81 },
      { id: "saiss_2022", name: "Romain Saïss", position: "DEF", age_at_tournament: 32, overall: 78 },
      { id: "aguerd_2022", name: "Nayef Aguerd", position: "DEF", age_at_tournament: 26, overall: 79 },
      { id: "bounou_2022", name: "Yassine Bounou", position: "GK", age_at_tournament: 31, overall: 84 },
    ],
  },
  south_korea_2002: {
    team: "South Korea",
    year: 2002,
    nation_code: "KR",
    flag: "🇰🇷",
    players: [
      { id: "ahn_2002", name: "Ahn Jung-Hwan", position: "FWD", age_at_tournament: 26, overall: 78 },
      { id: "hwang_2002", name: "Hwang Sun-Hong", position: "FWD", age_at_tournament: 32, overall: 75 },
      { id: "lee_young_pyo_2002", name: "Lee Young-Pyo", position: "DEF", age_at_tournament: 25, overall: 76 },
      { id: "hong_myung_bo_2002", name: "Hong Myung-Bo", position: "DEF", age_at_tournament: 33, overall: 80 },
      { id: "lee_woon_jae_2002", name: "Lee Woon-Jae", position: "GK", age_at_tournament: 30, overall: 77 },
    ],
  },
  usa_2002: {
    team: "USA",
    year: 2002,
    nation_code: "US",
    flag: "🇺🇸",
    players: [
      { id: "donovan_2002", name: "Landon Donovan", position: "MID", age_at_tournament: 20, overall: 78 },
      { id: "mcbride_2002", name: "Brian McBride", position: "FWD", age_at_tournament: 30, overall: 75 },
      { id: "reyna_2002", name: "Claudio Reyna", position: "MID", age_at_tournament: 28, overall: 77 },
      { id: "friedel_2002", name: "Brad Friedel", position: "GK", age_at_tournament: 31, overall: 78 },
      { id: "pope_2002", name: "Eddie Pope", position: "DEF", age_at_tournament: 29, overall: 73 },
    ],
  },
  poland_1974: {
    team: "Poland",
    year: 1974,
    nation_code: "PL",
    flag: "🇵🇱",
    players: [
      { id: "lato_1974", name: "Grzegorz Lato", position: "FWD", age_at_tournament: 24, overall: 86 },
      { id: "deyna_1974", name: "Kazimierz Deyna", position: "MID", age_at_tournament: 26, overall: 85 },
      { id: "szarmach_1974", name: "Andrzej Szarmach", position: "FWD", age_at_tournament: 23, overall: 81 },
      { id: "gadocha_1974", name: "Robert Gadocha", position: "MID", age_at_tournament: 27, overall: 79 },
      { id: "tomaszewski_1974", name: "Jan Tomaszewski", position: "GK", age_at_tournament: 26, overall: 82 },
    ],
  },
  denmark_2002: {
    team: "Denmark",
    year: 2002,
    nation_code: "DK",
    flag: "🇩🇰",
    players: [
      { id: "tomasson_2002", name: "Jon Dahl Tomasson", position: "FWD", age_at_tournament: 25, overall: 79 },
      { id: "gronkjaer_2002", name: "Jesper Grønkjær", position: "MID", age_at_tournament: 23, overall: 76 },
      { id: "henriksen_2002", name: "Michael Henriksen", position: "MID", age_at_tournament: 27, overall: 74 },
      { id: "sorensen_2002", name: "Thomas Sørensen", position: "GK", age_at_tournament: 25, overall: 77 },
      { id: "helveg_2002", name: "Thomas Helveg", position: "DEF", age_at_tournament: 30, overall: 75 },
    ],
  },
  sweden_1994: {
    team: "Sweden",
    year: 1994,
    nation_code: "SE",
    flag: "🇸🇪",
    players: [
      { id: "larsson_1994", name: "Henrik Larsson", position: "FWD", age_at_tournament: 22, overall: 77 },
      { id: "brolin_1994", name: "Tomas Brolin", position: "MID", age_at_tournament: 23, overall: 80 },
      { id: "dahlin_1994", name: "Martin Dahlin", position: "FWD", age_at_tournament: 25, overall: 82 },
      { id: "ravelli_1994", name: "Thomas Ravelli", position: "GK", age_at_tournament: 34, overall: 81 },
      { id: "andersson_1994", name: "Patrik Andersson", position: "DEF", age_at_tournament: 23, overall: 77 },
    ],
  },
  colombia_2014: {
    team: "Colombia",
    year: 2014,
    nation_code: "CO",
    flag: "🇨🇴",
    players: [
      { id: "rodriguez_2014", name: "James Rodríguez", position: "MID", age_at_tournament: 22, overall: 85 },
      { id: "falcao_2014", name: "Radamel Falcao", position: "FWD", age_at_tournament: 28, overall: 86 },
      { id: "cuadrado_2014", name: "Juan Cuadrado", position: "MID", age_at_tournament: 25, overall: 80 },
      { id: "yepes_2014", name: "Mario Yepes", position: "DEF", age_at_tournament: 38, overall: 77 },
      { id: "ospina_2014", name: "David Ospina", position: "GK", age_at_tournament: 25, overall: 79 },
    ],
  },
  mexico_2006: {
    team: "Mexico",
    year: 2006,
    nation_code: "MX",
    flag: "🇲🇽",
    players: [
      { id: "borgetti_2006", name: "Jared Borgetti", position: "FWD", age_at_tournament: 32, overall: 79 },
      { id: "marquez_2006", name: "Rafael Márquez", position: "DEF", age_at_tournament: 27, overall: 82 },
      { id: "torrado_2006", name: "Gerardo Torrado", position: "MID", age_at_tournament: 29, overall: 76 },
      { id: "ochoa_2006", name: "Guillermo Ochoa", position: "GK", age_at_tournament: 20, overall: 76 },
      { id: "zinha_2006", name: "Zinha", position: "MID", age_at_tournament: 32, overall: 77 },
    ],
  },
  uruguay_1970: {
    team: "Uruguay",
    year: 1970,
    nation_code: "UY",
    flag: "🇺🇾",
    players: [
      { id: "cubilla_1970", name: "Luis Cubilla", position: "FWD", age_at_tournament: 30, overall: 78 },
      { id: "morales_1970", name: "Victor Morales", position: "MID", age_at_tournament: 26, overall: 73 },
      { id: "mazurkiewicz_1970", name: "Ladislao Mazurkiewicz", position: "GK", age_at_tournament: 30, overall: 81 },
    ],
  },
  uruguay_2010: {
    team: "Uruguay",
    year: 2010,
    nation_code: "UY",
    flag: "🇺🇾",
    players: [
      { id: "suarez_2010", name: "Luis Suárez", position: "FWD", age_at_tournament: 23, overall: 84 },
      { id: "forlan_2010", name: "Diego Forlán", position: "FWD", age_at_tournament: 31, overall: 86 },
      { id: "cavani_2010", name: "Edinson Cavani", position: "FWD", age_at_tournament: 23, overall: 81 },
      { id: "lugano_2010", name: "Diego Lugano", position: "DEF", age_at_tournament: 29, overall: 79 },
      { id: "muslera_2010", name: "Fernando Muslera", position: "GK", age_at_tournament: 24, overall: 78 },
    ],
  },
  portugal_2016: {
    team: "Portugal",
    year: 2016,
    nation_code: "PT",
    flag: "🇵🇹",
    players: [
      { id: "ronaldo_cr_2016", name: "Cristiano Ronaldo", position: "FWD", age_at_tournament: 31, overall: 95 },
      { id: "quaresma_2016", name: "Ricardo Quaresma", position: "MID", age_at_tournament: 32, overall: 78 },
      { id: "renato_sanches_2016", name: "Renato Sanches", position: "MID", age_at_tournament: 18, overall: 77 },
      { id: "joao_mario_2016", name: "João Mário", position: "MID", age_at_tournament: 23, overall: 78 },
      { id: "fonte_2016", name: "José Fonte", position: "DEF", age_at_tournament: 32, overall: 78 },
      { id: "carvalho_rc_2016", name: "Ricardo Carvalho", position: "DEF", age_at_tournament: 38, overall: 76 },
      { id: "patricio_2016", name: "Rui Patrício", position: "GK", age_at_tournament: 28, overall: 82 },
    ],
  },
};

const outputDir = path.join(__dirname, "../public/data/squads");
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

for (const [key, squad] of Object.entries(squads)) {
  const filePath = path.join(outputDir, `${key}.json`);
  fs.writeFileSync(filePath, JSON.stringify(squad, null, 2));
  console.log(`✓ ${key}.json`);
}

console.log(`\nGenerated ${Object.keys(squads).length} squad files.`);
